/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    Comment: typeof import('./components/smallcomponents/Comment.vue')['default']
    ComponentsTemplate: typeof import('./components/smallcomponents/ComponentsTemplate.vue')['default']
    CreateGamePage: typeof import('./components/subpages/CreateGamePage.vue')['default']
    DecisionPage: typeof import('./components/subpages/DecisionPage.vue')['default']
    DesicionInput: typeof import('./components/smallcomponents/DesicionInput.vue')['default']
    GameDetailPage: typeof import('./components/subpages/GameDetailPage.vue')['default']
    HeaderTop: typeof import('./components/smallcomponents/HeaderTop.vue')['default']
    HeaderTopAfterLogin: typeof import('./components/smallcomponents/HeaderTopAfterLogin.vue')['default']
    Home: typeof import('./components/subpages/Home.vue')['default']
    InterPage: typeof import('./components/subpages/InterPage.vue')['default']
    LandingPage: typeof import('./components/subpages/LandingPage.vue')['default']
    LoginComponent: typeof import('./components/smallcomponents/LoginComponent.vue')['default']
    ManageGameDetailsPage: typeof import('./components/subpages/ManageGameDetailsPage.vue')['default']
    ManageGamePage: typeof import('./components/备份/ManageGamePage.vue')['default']
    RegisterComponent: typeof import('./components/smallcomponents/RegisterComponent.vue')['default']
    RegisterPage: typeof import('./components/subpages/RegisterPage.vue')['default']
    ResultOutput: typeof import('./components/smallcomponents/ResultOutput.vue')['default']
    ResultPage: typeof import('./components/subpages/ResultPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchBar: typeof import('./components/smallcomponents/SwitchBar.vue')['default']
    TestPage: typeof import('./components/subpages/TestPage.vue')['default']
    UserInfoPage: typeof import('./components/subpages/UserInfoPage.vue')['default']
  }
}
